### ISSUE TITLE
Deployment will fail if a controller without region exists in juju

### ISSUE THREAD

**Issue by camille-rodriguez** [juju-solutions/bundle-kubeflow#104]
I deployed following these instructions https://jaas.ai/kubeflow/bundle/120#setup-microk8s. 
At the step `python3 scripts/cli.py deploy-to uk8s` , the deployment fails towards the end with this error:

> DEBUG:root:pytorch-operator is lead by pytorch-operator/0
> DEBUG:root:ambassador-auth is lead by ambassador-auth/0
> juju kubectl apply -f 
> /home/crodriguez/bundle-kubeflow/scripts/../charms/pipelines-scheduledworkflow/resources/sa.yaml
> Error: YamlError(Message("missing field `region`", Some(Pos { marker: Marker { index: 1840, line: 
> 36, col: 8 }, path: "controllers.lxd-controller" })))
> Command '('juju', 'kubectl', 'apply', '-f', 
> '/home/crodriguez/bundle-kubeflow/scripts/../charms/pipelines-scheduledworkflow/resources/sa.yaml')' returned non-zero exit status 1.

I do have a controller without a region, but that is my lxd controller, it should not break the deployment of a model inside my uk8s controller. 
![image](https://user-images.githubusercontent.com/42066843/65777790-4d0b0080-e10a-11e9-84f7-cd15e2c9e7f0.png)

**Comment by knkski** [comment]
Can you do a snap refresh and try again? I pushed out an update to the `juju-helpers` snap that should fix this.

**Comment by camille-rodriguez** [comment]
Yep, that fixed it. Thanks!
