### ISSUE TITLE
python3 scripts/cli.py remove kubeflow fails because of persistent storage

### ISSUE THREAD

**Issue by camille-rodriguez** [juju-solutions/bundle-kubeflow#112]
Removal of the kubeflow model fails because of persistent storage. 
```
crodriguez@camille-hp:~/bundle-kubeflow$ python3 scripts/cli.py remove-from uk8s
+ juju destroy-model uk8s:kubeflow
WARNING! This command will destroy the "kubeflow" model.
This includes all containers, applications, data and other resources.

Continue [y/N]? y
Destroying modelERROR cannot destroy model "kubeflow"

The model has persistent storage remaining:
	3 volumes and 3 filesystems

To destroy the storage, run the destroy-model
command again with the "--destroy-storage" option.

To release the storage from Juju's management
without destroying it, use the "--release-storage"
option instead. The storage can then be imported
into another Juju model.
```

Command '('juju', 'destroy-model', 'uk8s:kubeflow')' returned non-zero exit status 1.

The juju command must have the --destroy-storage option to perform successfully.

**Comment by knkski** [comment]
We should make this flag more visible, but the wrapper script has a `--purge` option that will add in the `--destroy-storage` flag to `juju destroy-model`

**Comment by camille-rodriguez** [comment]
Why not suggest directly to use the juju command instead of doing a wrapper for a 1-liner?

**Comment by knkski** [comment]
@camille-rodriguez: Sorry about the slow response on this, but yeah, the wrapper is a bit much for a one-liner. Removing it in #117.
