### ISSUE TITLE
Ambassador redirects to https

### ISSUE THREAD

**Issue by grebennikov** [juju-solutions/bundle-kubeflow#163]
Deployed bundle #170
Ambassador is related to the gatekeeper and login.
Ambassador is exposed via loadbalancer on the default port 80.

When trying to access via clusterip/loadbalancer ip getting timeout.
curl to the address returns the following:
$ curl 172.29.146.13
<a href="https://172.29.146.13/kflogin">Temporary Redirect</a>.

Clearly the envoy redirects the traffic to the port 443 which there is no listener for.

**Comment by knkski** [comment]
The `kubeflow-gatekeeper` charm forces HTTPS connections, which requires that you use the nginx ingress for cert handling, as Ambassador never handles certs. #165 adds support for a different AuthService that handles HTTP connections just fine, so closing this
