### ISSUE TITLE
invalid charm url in application oidc-gatekeeper

### ISSUE THREAD

**Issue by camille-rodriguez** [juju-solutions/bundle-kubeflow#171]
The bundle cannot deploy.

crodriguez@camille-hp:~/bundle-kubeflow$ python3 scripts/cli.py deploy-to charmed-kubernetes-us-east-1
Enter a password to set for the Kubeflow dashboard: 
Repeat for confirmation: 
+ juju add-model kubeflow charmed-kubernetes
Added 'kubeflow' model on charmed-kubernetes/us-east-1 with credential 'charmed-kubernetes' for user 'admin'
+ juju deploy -m kubeflow kubeflow --channel stable --overlay=/tmp/tmpgl9nrt03
Located bundle "cs:bundle/kubeflow-170"
ERROR cannot deploy bundle: the provided bundle has the following errors:
empty charm path
invalid charm URL in application "oidc-gatekeeper": cannot parse URL "": name "" not valid
empty charm path
invalid charm URL in application "dex-auth": cannot parse URL "": name "" not valid
Command '('juju', 'deploy', '-m', 'kubeflow', 'kubeflow', '--channel', 'stable', '--overlay=/tmp/tmpgl9nrt03')' returned non-zero exit status 1.

Can we have a default bundle that deploys without needing to configure dex/oidc and simply give us a working kubeflow deployment for demo use? From what I read, we need to configure dex and oidc to be able to deploy it

**Comment by knkski** [comment]
Sorry about that. You'll need to use an older cli.py script that doesn't use dex:

https://github.com/juju-solutions/bundle-kubeflow/blob/e9a2775d95146fde4544657df951369eb3f86c58/scripts/cli.py

Working on getting an updated bundle pushed up to the charm store, blocked by https://github.com/juju/charmstore/issues/896

I'd like to avoid having a default bundle without any authentication, as it then becomes an easy malware vector. For demo purposes, you can either remove kubeflow-gatekeeper/oidc-gatekeeper, or configure static-username/static-password on dex-auth.

**Comment by knkski** [comment]
This should no longer be an issue with the latest stable version of the kubeflow bundle in the charm store.
