### ISSUE TITLE
when deploying with microk8s ingress gets broken on restart

### ISSUE THREAD

**Issue by grebennikov** [juju-solutions/bundle-kubeflow#173]
Windows-based deployment with multipass.
Because this is a VM I have to modify ingress to point to the <IP.xip.io> rather than to the localhost.
When I stop microk8s and start again, the value "localhost" is again set in the ingress, also "tls" section is gone.

**Comment by knkski** [comment]
Looks like this stems from https://bugs.launchpad.net/juju/+bug/1863013. In other words, when the Juju controller boots back up, it overwrites the existing Ingress, after we've patched it with TLS and whatnot. I think the short-term fix will to avoid `juju expose`, and just directly create an Ingress with kubectl.

**Comment by knkski** [comment]
Fixed by https://github.com/ubuntu/microk8s/pull/965
