### ISSUE TITLE
Installation on macOS not working

### ISSUE THREAD

**Issue by OnTheRicky** [juju-solutions/bundle-kubeflow#191]
ran `KUBEFLOW_DEBUG=true microk8s.enable kubeflow` and fails with the following:

Just trying to get a local kubeflow environment going with microk8s

Running: 
`macOS Catalina 10.15.4`
`multipass  1.1.0+mac`
`multipassd 1.1.0+mac`

> 17:52:06 DEBUG httpbakery client.go:243 client do GET https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/seldon-core-15/meta/any?include=id&include=supported-series&include=published {
17:52:07 DEBUG httpbakery client.go:245 } -> error <nil>
17:52:07 DEBUG juju.api monitor.go:35 RPC connection died
17:52:07 DEBUG juju.api monitor.go:35 RPC connection died
17:52:07 DEBUG juju.rpc server.go:328 error closing codec: write tcp 192.168.64.4:37816->10.152.183.80:17070: write: broken pipe
ERROR cannot deploy bundle: cannot add charm "cs:~kubeflow-charmers/seldon-core-15": connection is shut down
17:52:07 DEBUG cmd supercommand.go:519 error stack: 
/workspace/_build/src/github.com/juju/juju/rpc/client.go:14: connection is shut down
/workspace/_build/src/github.com/juju/juju/rpc/client.go:178: 
/workspace/_build/src/github.com/juju/juju/api/apiclient.go:1187: 
/workspace/_build/src/github.com/juju/juju/api/client.go:459: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/store.go:68: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/bundle.go:543: cannot add charm "cs:~kubeflow-charmers/seldon-core-15"
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/bundle.go:475: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/bundle.go:164: 
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/deploy.go:969: cannot deploy bundle
/workspace/_build/src/github.com/juju/juju/cmd/juju/application/deploy.go:1540: 

>Command '('microk8s-juju.wrapper', '--debug', 'deploy', 'cs:kubeflow', '--channel', 'stable', '--overlay', '/tmp/tmp46o45t78')' returned non-zero exit status 1
Failed to enable kubeflow

>22:10:04 DEBUG juju.kubernetes.provider events.go:51 getting the latest event for "involvedObject.name=controller,involvedObject.kind=StatefulSet"
22:10:04 INFO  juju.juju api.go:302 API endpoints changed from [] to [10.152.183.231:17070]
22:10:04 INFO  cmd controller.go:89 Contacting Juju controller at 10.152.183.231 to verify accessibility...
22:10:04 INFO  juju.juju api.go:67 connecting to API addresses: [10.152.183.231:17070]
22:20:02 ERROR juju.cmd.juju.commands bootstrap.go:776 unable to contact api server after 1 attempts: unable to connect to API: dial tcp 10.152.183.231:17070: connect: connection refused
22:20:02 DEBUG juju.cmd.juju.commands bootstrap.go:777 (error details: [{/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/juju/common/controller.go:128: unable to contact api server after 1 attempts} {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/juju/common/controller.go:44: } {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/modelcmd/modelcommand.go:405: } {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/modelcmd/modelcommand.go:424: } {/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/modelcmd/base.go:214: } {/build/juju/parts/juju/go/src/github.com/juju/juju/juju/api.go:72: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:207: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:622: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:967: } {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:1071: unable to connect to API} {/build/juju/parts/juju/go/src/github.com/juju/juju/api/apiclient.go:1096: } {dial tcp 10.152.183.231:17070: connect: connection refused}])

**Comment by OnTheRicky** [comment]
If running with `multipass` you need to allow traffic from host machine in/out off multipass: 

`multipass launch --name microk8s-vm --mem 12G --disk 40G`
`multipass exec microk8s-vm -- sudo snap install microk8s --classic`
`multipass exec microk8s-vm -- sudo iptables -P FORWARD ACCEPT` 🚀

then `microk8s.enable dns dashboard storage kubeflow` runs past this error... presently stuck on last pod not loading, which is another issue

**Comment by knkski** [comment]
Thanks @OnTheRicky, this should get documented somewhere

**Comment by evilnick** [comment]
closed in favour of: https://github.com/canonical-web-and-design/microk8s.io/issues/254
