### ISSUE TITLE
katib random example does not work

### ISSUE THREAD

**Issue by aym-frikha** [juju-solutions/bundle-kubeflow#211]
Hello,

after applying the random example for Katib, the random experiment stick on running but does never complete:

This is an output of one of the trials:
https://paste.ubuntu.com/p/XpqDWWSmfQ/

The pods are showing complete but they are not:

afrikha@afrikha-canonical:~/CPE/demos/bundle-kubeflow/lma$ kubectl get pods -n admin
NAME                                     READY   STATUS      RESTARTS   AGE
random-example-cfdbg84k-w7fx8            0/1     Completed   0          23m
random-example-cgpwrfvb-lv6wt            0/1     Completed   0          23m
random-example-lhzflq7t-6qb6g            0/1     Completed   0          23m
random-example-random-64b574949c-pmcpl   1/1     Running     0          24m

**Comment by knkski** [comment]
@aym-frikha: Can you post the output from `juju status`?

It looks like at least one of the kubeflow pods isn't there for you, judging by this message in your paste:

    transport: Error while dialing dial tcp: lookup katib-db-manager.kubeflow on 10.152.183.41:53: no such host

I tried this myself with a kubeflow deployment created by `microk8s.enable kubeflow`, and the experiment ran just fine.

**Comment by knkski** [comment]
I would guess that this is actually just a consequence of #210
