### ISSUE TITLE
[Question] How do I get the address of the Kubeflow Dashboard?

### ISSUE THREAD

**Issue by lqdev** [juju-solutions/bundle-kubeflow#223]
I was able to successfully deploy kubeflow with Microk8s and access the dashboard. However, I restarted my computer and was no longer able to access the site at the provided ambassador URL. Is there a way to get that address to make sure I'm pointing my browser to the correct address?

**Comment by knkski** [comment]
You'll want to connect to http://X.X.X.X.xip.io/, where `X.X.X.X` can be found with this command:

    microk8s.kubectl get -n kubeflow service/ambassador -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'

**Comment by knkski** [comment]
Alternatively, if you're using the `cli.py` script, you can run `python3 scripts/cli.py info uk8s` to show a little bit more information, such as how to retrieve the username/password

**Comment by lqdev** [comment]
Thanks @knkski
