### ISSUE TITLE
Break out setup into the deploy CK part and add-k8s

### ISSUE THREAD

**Issue by cjohnston1158** [juju-solutions/bundle-kubeflow#230]
Currently there are two options for deploying kubeflow on CK: deploy CK as part of the kubeflow setup, or have a CK environment manually add the k8s cloud, and then do deploy-to. There should be a way to do the full thing, or just add the k8s cloud.

**Comment by knkski** [comment]
You should be able to add and remove arbitrary Kubernetes clusters with these commands:

    python scripts/cli.py k8s add
    python scripts/cli.py k8s remove

Though these are both just thin wrappers around `juju add-k8s` and `juju remove-k8s`, respectively

**Comment by knkski** [comment]
Closing since I think this is handled, otherwise feel free to reopen
