### ISSUE TITLE
Can't create seldon deployment with volume

### ISSUE THREAD

**Issue by grebennikov** [juju-solutions/bundle-kubeflow#36]
When creating seldon deployment with no volumes - pods are getting created instantly.
When adding volume context as well as volume mount into the containers context - "describe seldondeployments" shows no event.

For reference - paste of the deployment I'm using.
https://pastebin.ubuntu.com/p/Wpcf3Gdb9s/

**Comment by grebennikov** [comment]
Update:
This is from the log of seldon cluster manager:
com.google.protobuf.InvalidProtocolBufferException: Cannot find field: nfs in message k8s.io.api.core.v1.Volume

Same happens if trying to define persistentVolumeClaim instead of NFS:
com.google.protobuf.InvalidProtocolBufferException: Cannot find field: persistentVolumeClaim in message k8s.io.api.core.v1.Volume

**Comment by grebennikov** [comment]
@knkski fyi

**Comment by knkski** [comment]
@grebennikov: Looks like you'll need to wrap the volume definition in `volumeSource`: https://github.com/SeldonIO/seldon-core/issues/116#issuecomment-373206582
